repos:
  - hooks:
      - id: fmt
      # - args:
      #     - --workspace
      #   id: cargo-check
      - id: clippy
        args: ["--", "-D", "warnings"]
    repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
