services:
  rauthy:
    build: .
    volumes:
      - rauthy-data:/app/data
      - rauthy-tls:/app/tls
    environment:
      LOCAL_TEST: "true"
      LOG_LEVEL: debug
      SWAGGER_UI_ENABLE: "true"
      SWAGGER_UI_PUBLIC: "true"

volumes:
  rauthy-data:
  rauthy-tls:
