name: Publish rauthy to GitHub Container Registry

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Setup & Build UI
        run: |
          just setup
          just build-ui

      - name: Build arm64
        env:
          JEMALLOC_SYS_WITH_LG_PAGE: 16
          PKG_CONFIG_ALLOW_CROSS: 1
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          cargo build --release --target aarch64-unknown-linux-gnu
          mv target/aarch64-unknown-linux-gnu/release/rauthy target/rauthy_arm64

      - name: Build x64
        env:
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: x86_64-linux-gnu-gcc
          PKG_CONFIG_ALLOW_CROSS: 1
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-x86-64-linux-gnu
          rustup target add x86_64-unknown-linux-gnu
          cargo build --release --target x86_64-unknown-linux-gnu
          mv target/x86_64-unknown-linux-gnu/release/rauthy target/rauthy_amd64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ !contains(github.ref, '-') }}

      - name: Build & push container
        uses: docker/build-push-action@v6
        with:
          context: "."
          push: true
          platforms: linux/amd64,linux/arm64
          attests: type=sbom
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}



