name: Release please

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Login to assistant app
        id: ghapp-auth
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.ASSISTANT_APP_ID }}
          private-key: ${{ secrets.ASSISTANT_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.ghapp-auth.outputs.token }}
